spring:
  application:
    name: catalog-service
  data:
    mongodb:
      #  On remplace localhost:27018 par mongodb:27017 (nom interne Docker)
      uri: mongodb://pokeadmin:pokepassword@mongodb:27017/catalog_db?authSource=admin
  cloud:
    consul:
      host: consul #  On remplace localhost par consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: catalog-service #  Nom du conteneur
        prefer-ip-address: false
        port: 8083
        health-check-path: /actuator/health

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 30000

server:
  port: 8083