spring:
  application:
    name: social-service
  data:
    mongodb:
      #  On vise le conteneur mongodb sur son port interne 27017
      uri: mongodb://pokeadmin:pokepassword@mongodb:27017/social_db?authSource=admin
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: social-service
        prefer-ip-address: false
        port: 8086
        health-check-path: /actuator/health
server:
  port: 8086