spring:
  # 1. Je donne un nom unique a ce microservice (son badge d'identite)
  application:
    name: identity-service

  # 2. Ici, je donne les coordonnees pour trouver ma base de donnees MySQL dans Docker
  datasource:
    # Je vise l'adresse localhost:3306 et la base poketcg_db creee sur Workbench
    url: jdbc:mysql://localhost:3306/poketcg_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 3. Hibernate traduit mon code Java en langage SQL automatiquement
  jpa:
    hibernate:
      # "update" dit a l'appli de creer les tables manquantes dans MySQL au demarrage
      ddl-auto: update
    # Je demande a voir le SQL dans la console d'IntelliJ pour verifier mes requetes
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # 4. Ici, mon microservice s'inscrit dans l'annuaire Consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # ASTUCE PRO : Je dis a Consul (dans Docker) de me chercher a l'adresse de mon PC (host.docker.internal)
        hostname: host.docker.internal
        prefer-ip-address: false
        port: 8081
        # On dit explicitement ou se trouve le test de santé
        health-check-path: /actuator/health
        health-check-interval: 10s

# 5. Je fixe le port sur 8081 pour eviter les conflits avec les autres services
server:
  port: 8081