spring:
  application:
    name: marketplace-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/poketcg_db?createDatabaseIfNotExist=true
    # ⭐ RIGUEUR : On utilise poke_user pour sécuriser la place de marché
    username: poke_user
    password: poke_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: marketplace-service
        prefer-ip-address: false
        port: 8085
server:
  port: 8085