services:
  # --- INFRASTRUCTURE ---
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_APP_USER}
      MYSQL_PASSWORD: ${MYSQL_APP_PWD}
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u root -p${MYSQL_ROOT_PWD}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
    ports:
      - "${MONGO_EXTERNAL_PORT}:27017"

  consul:
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "${CONSUL_EXTERNAL_PORT}:8500"
    command: "agent -dev -client 0.0.0.0"

  # --- MICROSERVICES ---
  identity-service:
    build: ./identity-service
    ports:
      - "${PORT_IDENTITY}:8081"
    depends_on:
      mysql-db:
        condition: service_started
      consul:
        condition: service_started
    restart: on-failure

  wallet-service:
    build: ./wallet-service
    ports:
      - "${PORT_WALLET}:8082"
    depends_on:
      mysql-db:
        condition: service_started
      consul:
        condition: service_started
    restart: on-failure

  catalog-service:
    build: ./catalog-service
    ports:
      - "${PORT_CATALOG}:8083"
    depends_on:
      mongodb:
        condition: service_started
      consul:
        condition: service_started
    restart: on-failure

  inventory-service:
    build: ./inventory-service
    ports:
      - "${PORT_INVENTORY}:8084"
    depends_on:
      mysql-db:
        condition: service_started
      consul:
        condition: service_started
    restart: on-failure

  marketplace-service:
    build: ./marketplace-service
    ports:
      - "${PORT_MARKETPLACE}:8085"
    depends_on:
      mysql-db:
        condition: service_started
      consul:
        condition: service_started
    restart: on-failure

  social-service:
    build: ./social-service
    ports:
      - "${PORT_SOCIAL}:8086"
    depends_on:
      mongodb:
        condition: service_started
      consul:
        condition: service_started
    restart: on-failure

  # --- FRONTEND ---
  webapp:
    image: nginx:alpine
    container_name: poketcg-site
    volumes:
      - ./webapp-service:/usr/share/nginx/html
    ports:
      - "${PORT_WEBAPP}:80"
    depends_on:
      - identity-service