version: '3.8'

services:
  # 1. MySQL
  mysql-db:
    image: mysql:8.0
    container_name: poketcg-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poketcg_db
    volumes:
      - mysql_data:/var/lib/mysql

  # 2. MongoDB (On change le port externe en 27018)
  mongodb:
    image: mongo:latest
    container_name: poketcg-mongodb
    ports:
      - "27018:27017" # Ton PC parlera au 27018 pour atteindre le 27017 du Docker
    environment:
      MONGO_INITDB_ROOT_USERNAME: pokeadmin
      MONGO_INITDB_ROOT_PASSWORD: pokepassword
    volumes:
      - mongo_data:/data/db

  # 3. Consul
  consul:
    image: hashicorp/consul:latest
    container_name: poketcg-consul
    ports:
      - "8500:8500"
    command: "agent -dev -client 0.0.0.0"

volumes:
  mysql_data:
  mongo_data: