spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/poketcg_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: wallet-service
        prefer-ip-address: false
        port: 8082
server:
  port: 8082