-- MySQL Script generated by MySQL Workbench
-- Sat Jun 13 11:43:55 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema poketcg_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema poketcg_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `poketcg_db` DEFAULT CHARACTER SET utf8 ;
USE `poketcg_db` ;

-- -----------------------------------------------------
-- Table `poketcg_db`.`dresseurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poketcg_db`.`dresseurs` ;

CREATE TABLE IF NOT EXISTS `poketcg_db`.`dresseurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  `role` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poketcg_db`.`portefeuille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poketcg_db`.`portefeuille` ;

CREATE TABLE IF NOT EXISTS `poketcg_db`.`portefeuille` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solde_disponible` DECIMAL(10,2) NOT NULL,
  `solde_sequestre` DECIMAL(10,2) NOT NULL,
  `id_dresseur` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_portefeuille_dresseurs_idx` (`id_dresseur` ASC) VISIBLE,
  CONSTRAINT `fk_portefeuille_dresseurs`
    FOREIGN KEY (`id_dresseur`)
    REFERENCES `poketcg_db`.`dresseurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poketcg_db`.`annonces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poketcg_db`.`annonces` ;

CREATE TABLE IF NOT EXISTS `poketcg_db`.`annonces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `carte_api_id` VARCHAR(50) NOT NULL,
  `prix` DECIMAL(10,2) NOT NULL,
  `statut` VARCHAR(20) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `id_dresseur` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_annonces_dresseurs1_idx` (`id_dresseur` ASC) VISIBLE,
  CONSTRAINT `fk_annonces_dresseurs1`
    FOREIGN KEY (`id_dresseur`)
    REFERENCES `poketcg_db`.`dresseurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poketcg_db`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poketcg_db`.`transaction` ;

CREATE TABLE IF NOT EXISTS `poketcg_db`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `montant` DECIMAL(10,2) NOT NULL,
  `statut_logistique` VARCHAR(30) NOT NULL,
  `date_paiement` DATETIME NOT NULL,
  `id_acheteur` INT NOT NULL,
  `id_vendeur` INT NOT NULL,
  `id_annonce` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_dresseurs1_idx` (`id_acheteur` ASC) VISIBLE,
  INDEX `fk_transaction_dresseurs2_idx` (`id_vendeur` ASC) VISIBLE,
  INDEX `fk_transaction_annonces1_idx` (`id_annonce` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_dresseurs1`
    FOREIGN KEY (`id_acheteur`)
    REFERENCES `poketcg_db`.`dresseurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_dresseurs2`
    FOREIGN KEY (`id_vendeur`)
    REFERENCES `poketcg_db`.`dresseurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_annonces1`
    FOREIGN KEY (`id_annonce`)
    REFERENCES `poketcg_db`.`annonces` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poketcg_db`.`cartes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poketcg_db`.`cartes` ;

CREATE TABLE IF NOT EXISTS `poketcg_db`.`cartes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_api_unique` VARCHAR(50) NOT NULL,
  `nom_fr` VARCHAR(100) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `serie_extension` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_api_unique_UNIQUE` (`id_api_unique` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poketcg_db`.`collectionner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poketcg_db`.`collectionner` ;

CREATE TABLE IF NOT EXISTS `poketcg_db`.`collectionner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `etat_carte` VARCHAR(20) NOT NULL,
  `langue_carte` VARCHAR(10) NOT NULL,
  `date_acquisition` DATETIME NULL,
  `id_dresseur` INT NOT NULL,
  `id_carte` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_collectionner_dresseurs1_idx` (`id_dresseur` ASC) VISIBLE,
  INDEX `fk_collectionner_cartes1_idx` (`id_carte` ASC) VISIBLE,
  CONSTRAINT `fk_collectionner_dresseurs1`
    FOREIGN KEY (`id_dresseur`)
    REFERENCES `poketcg_db`.`dresseurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collectionner_cartes1`
    FOREIGN KEY (`id_carte`)
    REFERENCES `poketcg_db`.`cartes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poketcg_db`.`news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poketcg_db`.`news` ;

CREATE TABLE IF NOT EXISTS `poketcg_db`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(150) NOT NULL,
  `contenu` TEXT NOT NULL,
  `image_illustration` VARCHAR(255) NULL,
  `date_publication` DATETIME NOT NULL,
  `id_admin` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_news_dresseurs1_idx` (`id_admin` ASC) VISIBLE,
  CONSTRAINT `fk_news_dresseurs1`
    FOREIGN KEY (`id_admin`)
    REFERENCES `poketcg_db`.`dresseurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poketcg_db`.`topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poketcg_db`.`topics` ;

CREATE TABLE IF NOT EXISTS `poketcg_db`.`topics` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(150) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `id_createur` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_topics_dresseurs1_idx` (`id_createur` ASC) VISIBLE,
  CONSTRAINT `fk_topics_dresseurs1`
    FOREIGN KEY (`id_createur`)
    REFERENCES `poketcg_db`.`dresseurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `poketcg_db`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `poketcg_db`.`messages` ;

CREATE TABLE IF NOT EXISTS `poketcg_db`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenu` TEXT NOT NULL,
  `date_envoi` DATETIME NOT NULL,
  `id_auteur` INT NOT NULL,
  `id_topic` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_dresseurs1_idx` (`id_auteur` ASC) VISIBLE,
  INDEX `fk_messages_topics1_idx` (`id_topic` ASC) VISIBLE,
  CONSTRAINT `fk_messages_dresseurs1`
    FOREIGN KEY (`id_auteur`)
    REFERENCES `poketcg_db`.`dresseurs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_topics1`
    FOREIGN KEY (`id_topic`)
    REFERENCES `poketcg_db`.`topics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
