spring:
  # 1. Je nomme mon service pour qu'il soit reconnu par les autres
  application:
    name: inventory-service

  # 2. Ma connexion à MySQL (On utilise la même base poketcg_db)
  datasource:
    url: jdbc:mysql://localhost:3306/poketcg_db?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 3. Hibernate va créer la table 'collectionner' automatiquement
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Pour voir les requêtes SQL dans la console

  # 4. Inscription dans l'annuaire Consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # Adresse pour que Docker (Consul) voit mon IntelliJ (PC)
        hostname: host.docker.internal
        prefer-ip-address: false
        port: 8084 # Ce service écoutera sur le port 8084

# 5. On fixe le port 8084 (Identity=8081, Wallet=8082, Catalog=8083)
server:
  port: 8084